// Code generated by "stringer -type=NmRadioFlags"; DO NOT EDIT.

package gonetworkmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NmRadioFlagsNone-0]
	_ = x[NmRadioFlagsWlanAvailable-1]
	_ = x[NmRadioFlagsWwanAvailable-2]
}

const _NmRadioFlags_name = "NmRadioFlagsNoneNmRadioFlagsWlanAvailableNmRadioFlagsWwanAvailable"

var _NmRadioFlags_index = [...]uint8{0, 16, 41, 66}

func (i NmRadioFlags) String() string {
	if i >= NmRadioFlags(len(_NmRadioFlags_index)-1) {
		return "NmRadioFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NmRadioFlags_name[_NmRadioFlags_index[i]:_NmRadioFlags_index[i+1]]
}
